### PR TITLE
Added feature to run Maistra web site in a local container.

### PR DESCRIPTION
**Pull request by olaf-meyer**
Extended make file to run Maistra website in a local container, so that contributors don't need to install Hugo and its dependencies on their computer.

### CODE REVIEW

**Comment by dgn** [comment]
Hi @olaf-meyer! Thanks for the contribution, makes a lot of sense. We already have an image you can use though, it's the one that our CI uses: `quay.io/maistra-dev/maistra-builder:2.0` - so you don't have to include a Dockerfile in your PR

**Review by brian-avery — APPROVED** [review]

**Comment by olaf-meyer** [comment]
Hi @dgn, do you know where I can find the source code for the quay.io/maistra-dev/maistra-builder:2.0? I would like to add a link to this project in the make file, so that it is clear what the content of the docker file is.

**Comment by dgn** [comment]
> Hi @dgn, do you know where I can find the source code for the quay.io/maistra-dev/maistra-builder:2.0? I would like to add a link to this project in the make file, so that it is clear what the content of the docker file is.

Sure, it's here: https://github.com/maistra/test-infra/blob/main/docker/maistra-builder_2.0.Dockerfile

**Comment by olaf-meyer** [comment]
Hello, I tried to fix the problems with the check-links and the linting. When I try to run the images `quay.io/maistra-dev/maistra-builder:2.1` or `quay.io/maistra-dev/maistra-builder:2.0`. I get this error message `./tools/checkLinks.sh: line 7: yq: command not found`. Is the ci build that is using these images working for you?

**Comment by dgn** [comment]
hey @olaf-meyer, those problems should have been resolved by https://github.com/maistra/maistra.github.io/pull/174 - you just have to rebase. Sorry for the churn

**Review by dgn — APPROVED** [review]

**Comment by dgn** [comment]
Okay, I clicked the button and let GitHub merge the `maistra-2.0` branch into yours again. It should pass now

Update: nevermind, spelling :( can you add `maistra` and `http` to the dict file?

**Comment by olaf-meyer** [comment]
Sorry for the delay. I was quite busy the last weeks.

**Comment by dgn** [comment]
> Sorry for the delay. I was quite busy the last weeks.

No worries at all. Thank you for your perseverance :slightly_smiling_face:

**Pull request merged**
