### PR TITLE
Fix edit link

### PR DESCRIPTION
**Pull request by brian-avery**

### CODE REVIEW

**Review by dgn — CHANGES_REQUESTED** [review]
moving too fast

**Comment by brian-avery** [comment]
@dgn for one of them. The other was by design :)

**Comment by brian-avery** [comment]
@dgn This seems like a "false?" positive. Hugo's website takes forever to load on my system right now.

**Review by dmitri-d — APPROVED** [review]

**Review by dgn — APPROVED** [review]

**Pull request merged**
