### PR TITLE
Updated bookinfo installation docs with instructions for default dest…

### PR DESCRIPTION
**Pull request by dmitri-d**
…ination rules

### CODE REVIEW

**Comment by JStickler** [comment]
@dmitri-d , are the oc commands in these instructions istiooc or oc?

**Comment by dmitri-d** [comment]
@JStickler: istiooc, I'll update the docs (in a dedicated PR).

**Comment by JStickler** [comment]
@dmitri-d, Thanks, I just want to be really clear if/when we're using the existing oc command or istiooc, so we don't confuse users.

**Comment by dmitri-d** [comment]
@JStickler: after thinking about this and asking around, turns out that it doesn't make a difference: both "oc" and "istiooc" can be used to install bookinfo. I'm going to keep things as is.

**Pull request merged**
