### PR TITLE
Updated PHONY to have the command on a separate line

### PR DESCRIPTION
**Pull request by brian-avery**
@dgn please try this and let me know if it works. Both work on my system.

### CODE REVIEW

**Review by jwendell — COMMENTED** [review]
I think the syntax is `.PHONE: <target>`, no? https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html

**Comment by brian-avery** [comment]
Yeah, that's what I'm thinking too. Does it build for you @jwendell ?

**Comment by jwendell** [comment]
I didn't try, but I don;t think your wrong syntax would cause a failure. It would not just work as intended.

**Review by jwendell — APPROVED** [review]

**Review by dgn — APPROVED** [review]
thanks brian!

**Comment by brian-avery** [comment]
Thank you.

**Pull request merged**
