### PR TITLE
Updated documentation for snippted istio_installation_minimal and for pilot

### PR DESCRIPTION
**Pull request by olaf-meyer**
Hello, 

I added the key ior to the snippet istio_installation_minimal.adoc, because the key is in the default ServiceMeshControlPlane template. Furthermore I moved the table for pilot->request to pilot and added a key jwksResolverExtraRootCA to this table.

Olaf

### CODE REVIEW

**Review by brian-avery — APPROVED** [review]
Thanks for the contribution @olaf-meyer. Looks great.

**Review by dgn — APPROVED** [review]
+1, thank you very much!

**Pull request merged**
