### PR TITLE
base Maistra docs on OSSM docs

### PR DESCRIPTION
**Pull request by brian-avery**
This PR updates the Maistra documentation to synchronize from the product documentation. After this is merged, the idea is that engineers will create new documentation changes, where they are applicable to both Maistra and OSSM, by opening a pull request for Service Mesh in the OpenShift docs repo where they will be reviewed by the documentation team. After these are merged, someone runs `make update-docs` in the Maistra documentation repo, which collects the Service Mesh documentation and updates it to work with Maistra. This can then be used to open a pull request to synchronize changes. Currently, the OpenShift documentation doesn't have a spell checker, link checker, or anything like that, so the Maistra infrastructure will check that content and any issues will need to be fixed in the product repo before docs can be merged. 

Details of OpenShift docs: 
* OpenShift docs are written with a [module/assembly system](https://redhat-documentation.github.io/modular-docs/#creating-concept-modules). Assemblies are rendered as individual pages while modules are components that make up a page. Modules are stored in a modules directory and topics in a topics directory. 
* A [topic index](https://github.com/openshift/openshift-docs/blob/master/_topic_map.yml#L2276) lists all of the assemblies that belong to a section. 
* An [attributes file](https://github.com/openshift/openshift-docs/blob/master/modules/ossm-document-attributes.adoc) contains common values used in the documentation. This is included in each file. 
* Aside from the top ID of a file, anchors are automatically generated for all headers. Any links to internal content should be cross links using [`xref:`](https://github.com/openshift/openshift-docs/blob/master/contributing_to_docs/doc_guidelines.adoc#internal-cross-references)

This PR updates Maistra's documentation to do the following when `make update-docs` is run: 
* Download the [topic index](https://github.com/openshift/openshift-docs/blob/master/_topic_map.yml) from the OpenShift docs repo. This is an index of all pages, referred to as "assemblies".
* Look in `_topic_map.yml` for the pages that are part of [OpenShift Service Mesh documentation ](https://github.com/openshift/openshift-docs/blob/master/_topic_map.yml#L2276). 
* For each page, recursively: 
   * download the page itself and look for "modules" within the page. Modules are similar to what are referred to as snippets in the Maistra documentation -- asciidoc files that are embedded as a subset of a page. These are included with an `include:` directive in the asciidoc. 
  * download any images referenced in the document. 
  * Massage the asciidoc as necessary. This includes: 
      * Adding a header into each page
      * Extract the ID of a document and add it to a header to let us create an anchor. The OpenShift documentation has a known issue where all top level links are broken. This fixes it within the Maistra docs so our link checker doesn't complain. From a user's perspective, HTML redirects the user to the top of the page by default, so the broken link isn't actually visible unless you scan the links. 
      * convert any links to documentation that is part of the OpenShift documentation but not the ServiceMesh documentation to point at the URL on the OpenShift docs site. 
      * Add a weight to the document such that they appear in the same order that they do in the topic index when the site is rendered. 
      * Replace references in the attributes file to OpenShift Service Mesh with Maistra

I have also added a patch directory. Changes for modules and topics in Maistra that don't apply to OSSM should be added to the patches directory. After docs are pulled in from OSSM, all patches in this directory are applied.

### CODE REVIEW

**Comment by brian-avery** [comment]
Fixing several of the issues here: https://github.com/openshift/openshift-docs/pull/28109

**Comment by brian-avery** [comment]
The rest of the failures in here are valid and fixed/reported in: 
* https://github.com/maistra/maistra.github.io/pull/174
* https://issues.redhat.com/browse/OSSMDOC-197?filter=-2
* https://issues.redhat.com/browse/THREESCALE-6537

@neal-timpe @JStickler @jwendell can you please take a look at this and let me know your thoughts? Preview is here: https://deploy-preview-172--maistra.netlify.app/

Future things I'd like to add (likely after) this PR is merged: 
* Manual mapping of assemblies to subcategories
* Fix edit links so that any users who come to Maistra.io and want to open a PR to fix an issue are instead redirected to the same page on the OpenShift docs
* Figure out what the process is for running `make update-docs` to pull down the latest docs changes. 
* Auto-generate the OpenShift version instead of manually adding it to the attributes file
* Integrate variables used with the release data where appropriate.

**Comment by brian-avery** [comment]
I've added fixes for OSSMDOC-197 here: https://github.com/openshift/openshift-docs/pull/28345/files

**Comment by brian-avery** [comment]
The only failure is now in THREESCALE-6537 (https://github.com/openshift/openshift-docs/pull/28259).

**Review by dgn — APPROVED** [review]
lgtm so far, but it seems that all the other 'original' maistra.io content is gone. is that intended?

**Comment by brian-avery** [comment]
Thanks. Yeah, the intent here is to overwrite any content that we already have with the Maistra development to continue where possible there. The content that was on our Maistra.io website should be a subset of content that's on the OSSM website. 

This has support for patches for content that applies to Maistra that doesn't apply to OSSM, but ideally all changes would go there first.

**Comment by brian-avery** [comment]
@neal-timpe @JStickler I've asked this of Heather and Vidya as well. Scanning through, it doesn't look like any of the 'original' Maistra content is missing from the OSSM docs. However, if you see anything please let me know. I'm happy to rewrite any of this and open PRs against the OSSM repo.

**Comment by dgn** [comment]
> Thanks. Yeah, the intent here is to overwrite any content that we already have with the Maistra development to continue where possible there. The content that was on our Maistra.io website should be a subset of content that's on the OSSM website.
> 
> This has support for patches for content that applies to Maistra that doesn't apply to OSSM, but ideally all changes would go there first.

Okay, thanks. I guess that makes sense, it makes sure we're not diverging from the OpenShift docs. We should find a process where we sketch out new content (e.g. for new features) that docs can then work with and add to the OCP docs

**Comment by dgn** [comment]
I'm missing this page in the product docs: https://maistra.io/docs/installation/installation-options/

**Comment by brian-avery** [comment]
+1. My current understanding is that the we will write documentation for new features and open PRs directly against the openshift docs repo, and the docs team will give feedback through code reviews. But I think that could use some ironing out. 

Those docs are here:https://deploy-preview-172--maistra.netlify.app/docs/ossm-custom-resources.html#ossm-cr-parameters_ossm-custom-resources-v2x

**Comment by dgn** [comment]
> Those docs are here:https://deploy-preview-172--maistra.netlify.app/docs/ossm-custom-resources.html#ossm-cr-parameters_ossm-custom-resources-v2x

Thank you! Didn't look under Custom Resources

**Comment by brian-avery** [comment]
No problem. I had trouble finding it too.

**Review by rcernich — APPROVED** [review]

**Pull request merged**
